### ISSUE TITLE
Dynamic require of "/home/runner/react-leaflet/node_modules/leaflet.markercluster/dist/MarkerCluster.css" is not supported

### ISSUE THREAD

**Issue by 217013462** [akursat/react-leaflet-cluster#13] opened 2022-06-24 17:51 UTC
![image](https://user-images.githubusercontent.com/101268150/175614982-61b5de4a-d751-4df2-b6bc-02afbb68424f.png)

Hi!
I kept getting this error message when I tried to use the latest version of react-leaflet-cluster.
Is there anyone know how to fix this issue?

**Comment by akursat** [comment] 2022-08-21 16:05
Duplicate of #6

**Closed by akursat** 2022-08-21 16:05 UTC
